def dreamhelp(msgh):
    outh = ""
    if len(msgh) == 1:
        outh += 'Use "/dreamhelp (option)" with one of the following options:\n'
        outh += "- Commmands\n"
        outh += "- Bonus\n"
        outh += "- Flags\n"
        outh += "- Leaderboard\n"
        outh += "- Undo"
    elif len(msgh) == 2:
        if msgh[1].capitalize() == "Commands":
            outh += '**Commands:**\n'
            outh += "- **Playing:**\n"
            outh += "-- dreamplay\n"
            outh += "-- dreamreveal\n"
            outh += "-- dreamleave\n"
            outh += "- **Adding:**\n"
            outh += "-- dreamadd\n"
            outh += "-- dreamfake\n"
            outh += "-- dreamAI\n"
            outh += "- **Info:**\n"
            outh += "-- dreamcount\n"
            outh += "-- dreamsend\n"
            outh += "-- dreamname\n"
            outh += "-- dreamprofile\n"
            outh += "-- dreamhelp\n"
            outh += "- **Functions:**\n"
            outh += "-- dreamskip\n"
            outh += "-- dreamreset\n"
            outh += "-- dreamundo"
        if msgh[1].capitalize() == "Bonus":
            outh += "**Bonuses:**\n"
            outh += "Underdog - The lowest scorer recieves +1 when they are correct and the highest scorer is incorrect. Underdog bonus scales with number of players incorrect from the top.\n"
            outh += "Streak - Recieve +1 for each correct answer on a streak of 5 or more. Streak bonus scales on streak intervals of 5.\n"
            outh += "Lone Wolf - If only one player is correct they recieve +1 (3+ players).\n"
            outh += "Early Bird - The fastest answer recieves +1 when they are correct and the slowest answer is incorrect.\n"
            outh += "Streak Breaker - When a streak of 5 or more is broken, all players correct recieve +1.\n"
            outh += "Irony - Recieve +1 for correct answer when the dreamer was incorrect.\n"
            outh += "**Pity Bonuses:**\n"
            outh += "Biggest Loser - Recieve +1 for 5 incorrect answers in a row.\n"
            outh += "Bottom Feeder - Receive +1 for remaining last place for 5 rounds.\n"
            outh += "**Rare Bonuses:**\n"
            outh += "Non-conformist - Achieve Lone Wolf bonus while every incorrect player guessed the same name (4+ players).\n"
            outh += "Mixed Bag - Achieve Lone Wolf bonus while every incorrect player guessed different names (4+ players)."
        if msgh[1].capitalize() == "Flags":
            outh += "**Flags:**\n"
            outh += "# = Number of players.\n"
            outh += "c = Censor names.\n"
            outh += "f = Include fake dreams.\n"
            outh += "AI = Include AI dreams.\n"
            outh += "b = Include bonus points.\n"
            outh += "--- NOTE: Number flag must be the first\n"
            outh += "-- ex: /dreamplay 3 b f"
        if msgh[1].capitalize() == "Undo":
            outh += "**Undo:**\n"
            outh += "If you have a problem with a dream you just added, you can undo it with this command:\n"
            outh += "/dreamundo [dream number] [dreamer name]\n"
            outh += "--- NOTE: only the most recent dream can be removed, for security reasons"
        if msgh[1].capitalize() == "Leaderboard":
            outh += "**Leaderboard:**\n"
            outh += "The leaderboard ranks players based on skill rating. The skill rating is calculated as follows:\n"
            outh += "R * ( ( C / 10 ) + S )\n"
            outh += "Where R is correct ratio, C is number of correct answers, and S is longest streak."
    return outh